# Generated by Django 5.1.5 on 2025-02-11 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('org_id', models.CharField(max_length=255)),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_duration', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField()),
                ('subject_questions', models.JSONField()),
                ('marking_scheme', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('que_id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('exam', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('MHT CET', 'MHT CET')], max_length=50)),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology')], max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=1)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Descriptive', 'Descriptive'), ('Numericals', 'Numericals')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('explain', models.TextField(blank=True, null=True)),
                ('marks', models.FloatField()),
                ('prev_year', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('chapter', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=1)),
                ('question_type', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=10)),
                ('is_used', models.BooleanField()),
                ('explain', models.TextField()),
                ('marks', models.FloatField()),
                ('prev_year', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_management.exam')),
            ],
        ),
    ]
