# Generated by Django 5.1.5 on 2025-01-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_batch_name_organization'),
        ),
    ]
