# Generated by Django 5.1.6 on 2025-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_batch_unique_together_batch_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(blank=True, max_length=255, null=True)),
                ('TestId', models.CharField(max_length=255)),
                ('TestDateTime', models.DateTimeField(auto_now_add=True)),
                ('BookmarkDateTime', models.DateTimeField(auto_now_add=True)),
                ('Subject', models.CharField(max_length=255)),
                ('Chapter', models.CharField(max_length=255)),
                ('QuestionId', models.CharField(blank=True, max_length=255, null=True)),
                ('Comments', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(blank=True, max_length=255, null=True)),
                ('TestId', models.CharField(max_length=255)),
                ('ScheduledBy', models.CharField(max_length=255)),
                ('TestStartTime', models.CharField(max_length=255)),
                ('TestEndTime', models.CharField(max_length=255)),
                ('TestDuration', models.CharField(max_length=255)),
                ('PaperDescription', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
                ('Comments', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(blank=True, max_length=255, null=True)),
                ('ScheduledBy', models.CharField(blank=True, max_length=255, null=True)),
                ('TestStartTime', models.DateTimeField(auto_now_add=True)),
                ('TestDuration', models.CharField(max_length=255)),
                ('PaperDescription', models.CharField(max_length=255)),
                ('QuestionId', models.CharField(blank=True, max_length=255, null=True)),
                ('Report', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(blank=True, max_length=255, null=True)),
                ('TestId', models.CharField(blank=True, max_length=255, null=True)),
                ('Examname', models.CharField(max_length=255)),
                ('Question', models.CharField(max_length=255)),
                ('Answer', models.CharField(max_length=255)),
                ('Marks', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(max_length=255)),
                ('TestDuration', models.CharField(blank=True, max_length=255, null=True)),
                ('DateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('TimeTaken', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=255)),
                ('Url', models.CharField(max_length=255)),
            ],
        ),
    ]
