# Generated by Django 5.1.6 on 2025-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_bookmarkquestion_scheduledpaper_studentreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='TotalMarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
