# Generated by Django 5.1.6 on 2025-02-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_studentresult_totalmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='ObtainedMarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
