# Generated by Django 5.1.5 on 2025-01-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('JEE', 'JEE Mains'), ('NEET', 'NEET'), ('MHT-CET', 'MHT-CET')], max_length=10)),
                ('num_questions', models.IntegerField()),
                ('exam_duration', models.IntegerField(help_text='Duration in minutes')),
                ('total_marks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
